export * from './auth.routes.js'
export * from './posts.routes.js'
export * from './testimonies.routes.js'
export * from './communityInfo.routes.js'
export * from './postsCategories.routes.js'
export * from './dashboard.routes.js'
export * from './users.routes.js'
