-- AlterTable
ALTER TABLE "Community" ALTER COLUMN "name" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "address" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "name_clap" SET DATA TYPE VARCHAR(150),
ALTER COLUMN "rif_community" SET DATA TYPE VARCHAR(20);
